/**
 * Build src/data/catalog/ingredients.generated.ts from the reviewed catalog draft.
 *   pnpm gen:catalog   (reads scripts/catalog-draft.json)
 * Edit scripts/catalog-draft.json to correct availability/family/etc., then re-run.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const rows = JSON.parse(readFileSync(join(ROOT, "scripts/catalog-draft.json"), "utf8")) as Array<{
  raw: string;
  canonicalId: string;
  canonicalNameUk: string;
  category: string;
  family: string | null;
  availability: "common" | "specialty" | "rare";
  isPantryStaple: boolean;
}>;

const norm = (s: string) =>
  s
    .normalize("NFC")
    .toLowerCase()
    .replace(/['’ʼ`]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .replace(/\s+/g, " ");

const canonical: Record<
  string,
  { id: string; nameUk: string; category: string; family: string | null; availability: string; isPantryStaple: boolean }
> = {};
const rawToId: Record<string, string> = {};
const normToId: Record<string, string> = {};

for (const r of rows) {
  if (!canonical[r.canonicalId]) {
    canonical[r.canonicalId] = {
      id: r.canonicalId,
      nameUk: r.canonicalNameUk,
      category: r.category,
      family: r.family,
      availability: r.availability,
      isPantryStaple: r.isPantryStaple,
    };
  }
  rawToId[r.raw] = r.canonicalId;
  normToId[norm(r.raw)] = r.canonicalId;
}

const out =
  `// AUTO-GENERATED by scripts/gen-catalog.ts from scripts/catalog-draft.json — do not edit by hand.\n` +
  `export type Availability = "common" | "specialty" | "rare";\n` +
  `export interface CanonicalIngredient { id: string; nameUk: string; category: string; family: string | null; availability: Availability; isPantryStaple: boolean; }\n\n` +
  `export const CANONICAL: Record<string, CanonicalIngredient> = ${JSON.stringify(canonical, null, 2)};\n\n` +
  `export const RAW_TO_ID: Record<string, string> = ${JSON.stringify(rawToId, null, 2)};\n\n` +
  `export const NORM_TO_ID: Record<string, string> = ${JSON.stringify(normToId, null, 2)};\n`;

mkdirSync(join(ROOT, "src/data/catalog"), { recursive: true });
writeFileSync(join(ROOT, "src/data/catalog/ingredients.generated.ts"), out);
console.log(
  `✓ wrote ingredients.generated.ts (${Object.keys(canonical).length} canonical, ${Object.keys(rawToId).length} raw mappings)`,
);
