/**
 * Regenerate recipes/index.ts:  pnpm gen:index
 *
 * Statically imports every recipe.json (sorted by card number) and re-exports them as a
 * typed `Cocktail[]`. The cast is safe because `pnpm validate` guarantees each file matches
 * the schema. Re-run whenever a recipe folder is added.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const RECIPES_DIR = join(ROOT, "recipes");

const entries = readdirSync(RECIPES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => {
    const json = JSON.parse(readFileSync(join(RECIPES_DIR, d.name, "recipe.json"), "utf8"));
    return { folder: d.name, cardNumber: json.cardNumber as number };
  })
  .sort((a, b) => a.cardNumber - b.cardNumber);

const lines = [
  "// AUTO-GENERATED by scripts/gen-index.ts — do not edit by hand.",
  'import type { Cocktail } from "../src/types/cocktail.js";',
  ...entries.map((e) => `import r${e.cardNumber} from "./${e.folder}/recipe.json" with { type: "json" };`),
  "",
  `export const cocktails: Cocktail[] = [${entries.map((e) => `r${e.cardNumber}`).join(", ")}] as Cocktail[];`,
  "export default cocktails;",
  "",
];

writeFileSync(join(RECIPES_DIR, "index.ts"), lines.join("\n"));
console.log(`✓ wrote recipes/index.ts (${entries.length} recipe(s))`);
