/**
 * Generate Metro/Expo-safe data modules for the app:  pnpm gen:app-data
 *
 * The node-side `recipes/index.ts` uses `with { type: "json" }` import assertions + `.js`
 * extensions, which Metro can't bundle. This emits RN-friendly modules instead:
 *   - src/data/generated/cocktails.ts  — the full typed Cocktail[] inlined (no JSON imports)
 *   - src/data/generated/images.ts     — id -> { front, back } require() map (Metro asset ids)
 * Re-run whenever recipes change. Keeps the existing node pipeline (gen-index.ts) intact.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const RECIPES = join(ROOT, "recipes");
const OUT = join(ROOT, "src", "data", "generated");
mkdirSync(OUT, { recursive: true });

const folders = readdirSync(RECIPES, { withFileTypes: true })
  .filter((d) => d.isDirectory() && /^\d{3}-/.test(d.name))
  .map((d) => d.name)
  .map((name) => ({ name, json: JSON.parse(readFileSync(join(RECIPES, name, "recipe.json"), "utf8")) }))
  .sort((a, b) => a.json.cardNumber - b.json.cardNumber);

// cocktails.ts — inlined typed array (type-checked against Cocktail at compile time)
const cocktailsTs =
  `// AUTO-GENERATED by scripts/gen-app-data.ts — do not edit.\n` +
  `import type { Cocktail } from "../../types/cocktail";\n\n` +
  `export const cocktails: Cocktail[] = ${JSON.stringify(
    folders.map((f) => f.json),
    null,
    2,
  )};\n\n` +
  `export default cocktails;\n`;
writeFileSync(join(OUT, "cocktails.ts"), cocktailsTs);

// images.ts — require() map (only for recipes that actually have webp files on disk).
const entries = folders.flatMap((f) => {
  const parts: string[] = [];
  if (existsSync(join(RECIPES, f.name, "front.webp")))
    parts.push(`front: require("../../../recipes/${f.name}/front.webp")`);
  if (existsSync(join(RECIPES, f.name, "back.webp")))
    parts.push(`back: require("../../../recipes/${f.name}/back.webp")`);
  return parts.length ? [`  ${JSON.stringify(f.json.id)}: { ${parts.join(", ")} },`] : [];
});
const imagesTs =
  `// AUTO-GENERATED by scripts/gen-app-data.ts — do not edit.\n` +
  `import type { ImageSourcePropType } from "react-native";\n\n` +
  `export type CardImages = { front?: ImageSourcePropType; back?: ImageSourcePropType };\n\n` +
  `export const cardImages: Record<string, CardImages> = {\n${entries.join("\n")}\n};\n\n` +
  `export default cardImages;\n`;
writeFileSync(join(OUT, "images.ts"), imagesTs);

console.log(`✓ wrote src/data/generated/cocktails.ts + images.ts (${folders.length} recipes)`);
